### ISSUE TITLE
Hovering over nav items should show drop down menus

### ISSUE THREAD

**Issue by wunmi-design** [Myoats/preprod#12]
On large devices hovering over My account and the ellipses should show the menu. Currently the menu shows when you click on the nav items.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by penglididiom** [comment]
the feature was not there yesterday, but when I try to work on it, i noticed the feature has been implemented. https://www.myoats.com:4503/designlist.aspx/tab1-5
did you fix it?

**Comment by wunmi-design** [comment]
I did not fix this. I'm not sure why it works.
