### ISSUE TITLE
Place New About Myoats Card on Homepage

### ISSUE THREAD

**Issue by wunmi-design** [Myoats/preprod#18]

**Comment by penglididiom** [comment]
where is the new about myoats card?

**Comment by wunmi-design** [comment]
@penglididiom 
Find the about card in the 01-home-logged-out.html
https://www.dropbox.com/s/5wy04stka68vcnt/180410.zip?dl=0

Let's have it show for all users.

**Comment by wunmi-design** [comment]
@penglididiom 
The new About Card looks different. It looks like this:
![image](https://user-images.githubusercontent.com/37152320/39223300-3e95c43a-480f-11e8-9313-904b971cbd5d.png)

Find the about card in the 01-home-logged-out.html
https://www.dropbox.com/s/5wy04stka68vcnt/180410.zip?dl=0
