### ISSUE TITLE
Hide the file button on the Edit Profile Image Modal

### ISSUE THREAD

**Issue by wunmi-design** [Myoats/preprod#20]
I would like to get people to upload better avatars. Can we clean up this page by 
- changing the button to say Choose File instead of No File Chosen
- hide the small grey file button in the Edit Profile Modal seen here:
![image](https://user-images.githubusercontent.com/37152320/38292818-1b3e77b4-37b3-11e8-891b-0d9a3eb65092.png)
 

Here is documentation on how to  hide this button
https://stackoverflow.com/questions/572768/styling-an-input-type-file-button

**Comment by penglididiom** [comment]
fixed, please verify
