### ISSUE TITLE
Install Stripe

### ISSUE THREAD

**Issue by Myoats** [Myoats/preprod#3]
https://stripe.com/

**Comment by penglididiom** [comment]
it turns out stripe.net requires Visual studio 2015 or 2017. in our server, visual studio 2012 was installed, i am trying to install VS 2017 community version

**Comment by penglididiom** [comment]
installed VS 2017 and installed stripe.net to preprod site

**Comment by wunmi-design** [comment]
@penglididiom How is this coming along?
