### ISSUE TITLE
When I press settings from the Nav menu or tabs in the account the page is scrolled down when it loads. It also redirects to a Designs page. 

### ISSUE THREAD

**Issue by wunmi-design** [Myoats/preprod#30]
When I click on Alerts in the drop down from the Nav, it takes me to My Designs page

**Comment by penglididiom** [comment]
it has been fixed already

**Comment by wunmi-design** [comment]
It still loads to a scrolled position:
http://g.recordit.co/etumHurcNM.gif

**Comment by penglididiom** [comment]
fixed
