### ISSUE TITLE
Can we use a custom modal instead of the system modal in these instances

### ISSUE THREAD

**Issue by wunmi-design** [Myoats/preprod#33]
Can we use custom modals in these instances:

**The html is here:**
https://www.dropbox.com/s/klxyz6a53m6l8id/180529.zip?dl=0
use the Upgrade Confirmed Modal from 14-modals.html

# When a user updates their settings
**The title of the modal should say** 
"Update Confirmed"

**The copy should say** 
"Account has been updated successfully! "

**Visualization** 
![image](https://user-images.githubusercontent.com/37152320/40797671-04e4b180-64d7-11e8-8f2c-44ba8020a5fe.png)

# When a user deletes a comment
**The title of the modal should say** 
"Delete Comment"

**The copy should say** 
"Are you sure you want to delete this comment? "

**Visualization** 
![image](https://user-images.githubusercontent.com/37152320/40887531-49c82352-6718-11e8-82be-716e5e1e7925.png)

**Comment by WunmiAtewologun** [comment]
@penglididiom 
In addition, when someone Reports Abuse, the modal system alert modal should not show.

This is what we see now:
![image](https://user-images.githubusercontent.com/37152320/39312499-b8c9d6ae-493d-11e8-99ed-cd7b38f16d39.png)

 let's use the Upgrade Confirmed Modal from 14-modals.html
The html is here:
https://www.dropbox.com/s/5wy04stka68vcnt/180410.zip?dl=0

The title of the modal should say "Message Sent"
The copy should say "We will investigate and address your concern momentarily. "

**Comment by WunmiAtewologun** [comment]
When a user updates their pass, the system modal shows up. Can it be our custom modal

let's use the Upgrade Confirmed Modal from 14-modals.html
The html is here:
https://www.dropbox.com/s/5wy04stka68vcnt/180410.zip?dl=0

The title of the modal should say "Update Confirmed"
The copy should say "Account has been updated successfully! "

![image](https://user-images.githubusercontent.com/37152320/40797671-04e4b180-64d7-11e8-8f2c-44ba8020a5fe.png)

**Comment by penglididiom** [comment]
fixed

**Comment by wunmi-design** [comment]
When I delete my own comment, I see the system modal instead of the custom modal:
![image](https://user-images.githubusercontent.com/37152320/42170838-a319a97e-7de5-11e8-89f3-041ed6d8b43c.png)

**Comment by penglididiom** [comment]
this is a confirm modal, not alert modal. can you draft a confirm modal with "OK"/"Cancel" buttons?

**Comment by wunmi-design** [comment]
Can you use the Delete Modal 
The title of the modal should say
"Delete Comment"

The copy should say
"Are you sure you want to delete this comment? "

The html is here:
https://www.dropbox.com/s/klxyz6a53m6l8id/180529.zip?dl=0
use the Delete Modal from 14-modals.html

**Comment by penglididiom** [comment]
done, please verify
