### ISSUE TITLE
Pressing Contact Us in the nav should open this modal.

### ISSUE THREAD

**Issue by Myoats** [Myoats/preprod#4]

**Comment by wunmi-design** [comment]
For some reason, the current form that pops up doesn't send anything to feedback@myoats.com so let's just have the contact modal look like this:

Here is a visualization:
http://g.recordit.co/Mc4htln4qj.gif

Here is the link, in 14-modals.html, click on "Contact Us"
https://www.dropbox.com/s/kyu4c4zylcoogi7/180326.zip?dl=0
