### ISSUE TITLE
Change copy of sharing on FB

### ISSUE THREAD

**Issue by wunmi-design** [Myoats/preprod#68]
When we share an image on FB,
**This is what we see**
![image](https://user-images.githubusercontent.com/37152320/42177671-92b133ca-7dfb-11e8-8885-3c5ab9756848.png)

Instead, can it the title say "Title of design" 
and the copy say: "Illustrated by Username"
Here is a visualization:
![image](https://user-images.githubusercontent.com/37152320/42178125-31a4160e-7dfd-11e8-8885-5d7fa137310c.png)

**Comment by penglididiom** [comment]
done
