### ISSUE TITLE
Can you make a page which shows a table of the amount of Myoats 2 designs (including Private) each user has.

### ISSUE THREAD

**Issue by wunmi-design** [Myoats/preprod#72]
It can be similar to this page:
https://www.myoats.com/WunmiMonitor/WwUuDDMonitorLogin.aspx

**Comment by penglididiom** [comment]
done
https://www.myoats.com/WunmiMonitor/WwUuDDUserDesignList.aspx

**Comment by wunmi-design** [comment]
@penglididiom 
can you indicate the 
amount of users on the list,
and the total amount of:
users with 12 or more designs
users with 11 designs
users with 10 designs
users with 9 designs
users with 8 designs
users with 7 designs
users with 6 designs
users with 5 design
users with 4 designs
users with 3 designs
users with 2 designs
users with 1 design 

The format can be the same as how you indicate important info on this page:
![image](https://user-images.githubusercontent.com/37152320/42700681-7abf27c8-8692-11e8-9029-5224ccd284cb.png)
